@version: 3.38

options {
    chain_hostnames(no);
    flush_lines(1);
    keep_hostname(yes);
    stats(freq(0));
    use_dns(no);
};

source s_network {
    network(ip("0.0.0.0") port(1514) transport("udp") flags(no-parse));
    network(ip("0.0.0.0") port(1514) transport("tcp") flags(no-parse));
};

destination d_collector {
    network(
        "collector"
        port(5514)
        transport("udp")
        template("PBP_SYSLOG_SOURCE=${SOURCEIP} ${MESSAGE}\n")
    );
};

log {
    source(s_network);
    destination(d_collector);
    flags(flow-control);
};
